name: Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    name: ${{ matrix.python-version }} ${{ matrix.type-of-tests }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install core deps
        run: python -m pip install ".[test]"
      - name: Run unit tests
        run:  make tests
      - name: Upload code coverage report
        if: ${{ matrix.python-version == '3.11' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ${{ github.workspace }}/coverage.xml
          verbose: true